name: "Build, test and pack WebExtension"

on:
  push:
    branches:
      - master

jobs:
  Validate-json-and-zip:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Validate_manifest.json_of_the_extension
        uses: cardinalby/schema-validator-action@v1
        with:
          file: ${{ env.EXTENSION_DIR }}manifest.json
          schema: 'https://json.schemastore.org/webextension.json'

      - name: Pack directory to zip
        if: inputs.doNotPackZip != 'true'
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: ${{ env.EXTENSION_DIR }}
          zipFilePath: ${{ env.ZIP_FILE_PATH }}
