name: "Build, test and pack WebExtension"

on:
  push:
    branches:
      - master

jobs:
  Validate-json-and-zip:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Pack directory to zip
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: ${{ env.EXTENSION_DIR }}
          zipFilePath: ${{ env.ZIP_FILE_PATH }}
